package dev.kosmo.com.br.enuns;

public enum SituacaoEnum {

    AGUARDANDOLIGACAO(1),
    AGUARDANDOATENDIMENTO(2),
    ATENDIMENTOCONFIRMADOPELOCLIENTE(3),
    ATENDIMENTONAOCONFIRMADOPELOCLIENTE(4),
    ATENDIDO(5),
    NAOATENDIDO(6),
    ATENDIMENTOCOMRESPOSTASDIVERGENTES(7),
    CLIENTECONFIRMOUFECHAMENTODETRABALHO(8),
    CLIENTENAOCONFIRMOUFECHAMENTODETRABALHO(9),
    TRABALHOFECHADO(10),
    TRABALHONAOFECHADO(11),
    FECHAMENTODETRABALHOCOMRESPOSTASDIVERGENTES(12),
    CLIENTECONFIRMOUFINALIZACAODOTRABALHO(13),
    CLIENTENAOCONFIRMOUFINALIZACAODOTRABALHO(14),
    TRABALHOFINALIZADO(15),
    TRABALHONAOFINALIZADO(16),
    FINALIZACAODOTRABALHOCOMRESPOSTASDIVERGENTES(17);

    private final int id;
    SituacaoEnum(int id) { this.id = id; }
    public int getValue() { return id; }

}
